language: python

sudo: false

python:
  - "3.8"

env:
  global:
    - AWS_REGION=eu-central-1

cache: npm

before_script:
  - nvm install 12
  - nvm use 12
  - npm i

skript: echo "no tests 😟"

deploy:
  - provider: script
    skip_cleanup: true
    script: STAGE=staging npx serverless deploy
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: STAGE=prod npx serverless deploy
    on:
      branch: production
